// Code generated by gtkbuilder. DO NOT EDIT.

package main

import (
	"github.com/diamondburned/gotk4-adwaita/pkg/adw"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
)

type MainWindow struct {
	*adw.ApplicationWindow

	ToastOverlay   *adw.ToastOverlay
	StatusSwitch   *gtk.Switch
	MainMenuButton *gtk.MenuButton
	PeersStack     *gtk.Stack
}

func NewMainWindow(app *gtk.Application) *MainWindow {
	parent := adw.NewApplicationWindow(app)
	parent.SetObjectProperty("content", "ToastOverlay")
	parent.SetObjectProperty("default-height", 600)
	parent.SetObjectProperty("default-width", 800)
	parent.SetObjectProperty("title", "Trayscale")

	return &MainWindow{
		ApplicationWindow: parent,
	}
}

type PeerPage struct {
	*adw.StatusPage

	IPGroup          *adw.PreferencesGroup
	MiscGroup        *adw.PreferencesGroup
	ExitNodeRow      *adw.ActionRow
	ExitNodeSwitch   *gtk.Switch
	OnlineRow        *adw.ActionRow
	Online           *gtk.Image
	LastSeenRow      *adw.ActionRow
	LastSeen         *gtk.Label
	CreatedRow       *adw.ActionRow
	Created          *gtk.Label
	LastWriteRow     *adw.ActionRow
	LastWrite        *gtk.Label
	LastHandshakeRow *adw.ActionRow
	LastHandshake    *gtk.Label
	RxBytesRow       *adw.ActionRow
	RxBytes          *gtk.Label
	TxBytesRow       *adw.ActionRow
	TxBytes          *gtk.Label
}

func NewPeerPage() *PeerPage {
	parent := adw.NewStatusPage()

	return &PeerPage{
		StatusPage: parent,
	}
}
